// ============================================================================
// NotificationsController.cs
// ============================================================================
// Purpose: Manages user notifications including retrieval, pagination, marking
//          as read, and unread count tracking. Part of the Notification Service
//          which handles real-time alerts and updates for users.
// 
// Architecture: Uses MediatR CQRS pattern. All endpoints require JWT authentication.
//          Notifications are generated by various services (Payment, Billing, Card)
//          via event-driven messaging (RabbitMQ/MassTransit) and consumed by
//          this service's message consumers.
//
// Endpoints:
//   GET    /api/notifications/user/{userId}           - Get paginated notifications
//   GET    /api/notifications/user/{userId}/unread-count - Get unread notification count
//   PUT    /api/notifications/{notificationId}/read   - Mark single notification as read
//   PUT    /api/notifications/user/{userId}/read-all  - Mark all notifications as read
// ============================================================================

using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NotificationService.Application.Commands.MarkNotificationRead;
using NotificationService.Application.Commands.MarkAllRead;
using NotificationService.Application.Queries.GetNotifications;
using NotificationService.Application.Queries.GetUnreadCount;

namespace NotificationService.API.Controllers;

[ApiController]
[Route("api/notifications")]
[Produces("application/json")]
[Authorize]
public class NotificationsController(ISender mediator) : ControllerBase
{
    // -------------------------------------------------------------------------
    // GET /api/notifications/user/{userId}
    // Purpose: Retrieve paginated notifications for a specific user with optional filtering
    // Input: userId (GUID), isRead filter (optional), page number, page size
    // Output: ApiResponse<List<NotificationResponse>> with paginated notifications
    // Notes: Supports filtering by read/unread status. Default pagination is 
    //        page=1, pageSize=20. Used for notification center UI.
    // -------------------------------------------------------------------------
    /// <summary>Get paginated notifications for a user</summary>
    [HttpGet("user/{userId:guid}")]
    [ProducesResponseType(typeof(FinVault.Shared.Contracts.Responses.ApiResponse<
        List<FinVault.Shared.Contracts.Notification.Responses.NotificationResponse>>), 200)]
    public async Task<IActionResult> GetNotifications(
        Guid userId,
        [FromQuery] bool? isRead = null,
        [FromQuery] int page = 1,
        [FromQuery] int pageSize = 20,
        CancellationToken ct = default)
    {
        var query = new GetNotificationsQuery(userId, isRead, page, pageSize);
        var result = await mediator.Send(query, ct);
        return Ok(result);
    }

    // -------------------------------------------------------------------------
    // GET /api/notifications/user/{userId}/unread-count
    // Purpose: Get the count of unread notifications for a user
    // Input: userId (GUID)
    // Output: ApiResponse with unread count integer
    // Notes: Lightweight endpoint used to show notification badge count in UI.
    //        Returns only the count, not the actual notifications.
    // -------------------------------------------------------------------------
    /// <summary>Get unread notification count for a user</summary>
    [HttpGet("user/{userId:guid}/unread-count")]
    public async Task<IActionResult> GetUnreadCount(Guid userId, CancellationToken ct)
    {
        var query = new GetUnreadCountQuery(userId);
        var result = await mediator.Send(query, ct);
        return Ok(result);
    }

    // -------------------------------------------------------------------------
    // PUT /api/notifications/{notificationId}/read
    // Purpose: Mark a single specific notification as read
    // Input: notificationId (GUID) in URL path
    // Output: ApiResponse indicating success/failure of marking as read
    // Notes: Called when user clicks/opens a notification. Updates the 
    //        IsRead flag in the database for that notification.
    // -------------------------------------------------------------------------
    /// <summary>Mark a single notification as read</summary>
    [HttpPut("{notificationId:guid}/read")]
    public async Task<IActionResult> MarkRead(Guid notificationId, CancellationToken ct)
    {
        var cmd = new MarkNotificationReadCommand(notificationId);
        var result = await mediator.Send(cmd, ct);
        return Ok(result);
    }

    // -------------------------------------------------------------------------
    // PUT /api/notifications/user/{userId}/read-all
    // Purpose: Mark all notifications as read for a user in bulk
    // Input: userId (GUID)
    // Output: ApiResponse indicating success/failure and count of notifications marked read
    // Notes: "Mark all as read" button functionality. More efficient than 
    //        calling individual read endpoint for each notification.
    // -------------------------------------------------------------------------
    /// <summary>Mark all notifications as read for a user</summary>
    [HttpPut("user/{userId:guid}/read-all")]
    public async Task<IActionResult> MarkAllRead(Guid userId, CancellationToken ct)
    {
        var cmd = new MarkAllReadCommand(userId);
        var result = await mediator.Send(cmd, ct);
        return Ok(result);
    }
}
